-- CREATE TABLE DETAIL_BUKU 
CREATE TABLE DETAIL_BUKU
(
  ID_BUKU NUMBER NOT NULL,
  JUDUL_BUKU VARCHAR2(30) NOT NULL,
  PENGARANG_BUKU VARCHAR2(20) NOT NULL,
  PENERBIT_BUKU VARCHAR2(15) NOT NULL,
  TANGGAL_TERBIT_BUKU DATE,
  TEBAL_BUKU VARCHAR2(5) NOT NULL,
  STATUS_BUKU NUMBER
)

--VIEW DATA BUKU
SELECT * FROM DETAIL_BUKU;

--INSERT/CREATE DATA BUKU KE TABLE DETAIL_BUKU
INSERT INTO DETAIL_BUKU
  (ID_BUKU,
   JUDUL_BUKU,
   PENGARANG_BUKU,
   PENERBIT_BUKU,
   TANGGAL_TERBIT_BUKU,
   TEBAL_BUKU)
VALUES
  ('A0001',
   'HARRY POTTER DAN BATU BERTUAH',
   'J.K ROWLING',
   'GRAMEDIA',
   '29-JUN-1997',
   '384');

-- CREATE TABLE PEMINJAM_BUKU 
CREATE TABLE PEMINJAM_BUKU
(
  ID_PEMINJAM NUMBER NOT NULL,
  NAMA_PEMINJAM VARCHAR2(20) NOT NULL,
  TANGGAL_PINJAM DATE,
  TANGGAL_KEMBALI DATE
)

--INSERT DATA PEMINJAM KE TABLE PEMINJAM_BUKU
INSERT INTO PEMINJAM_BUKU
  (ID_PEMINJAM,
   NAMA_PEMINJAM,
   TANGGAL_PINJAM,
   TANGGAL_KEMBALI)
VALUES
  ('P0001',
   'DONNY',
   '13 OCT 2022',
   '20 OCT 2022');

--UPDATE DATA BUKU
UPDATE DETAIL_BUKU SET STATUS_BUKU = '1' WHERE STATUS_BUKU = '0';

--DELETE DATA BUKU
DELETE FROM DETAIL_BUKU WHERE ID_BUKU = 'A0001';
